eventhubNamespaces:
  - endpoint: beg-int-eh.servicebus.windows.net
    storageAccountEndpoint: beginteh.blob.core.windows.net
    checkpointContainer: checkpoints

exporter:
  appInsights:
    enabled: true
  prometheus:
    enabled: true
    port: 9090
    readTimeout: 1s

collector:
  interval: 2m
  concurrency: 10

log:
  level: "debug"
