apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eventhub-metrics.fullname" . }}
  labels:
    app: {{ template "eventhub-metrics.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}
