apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eventhub-metrics.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "eventhub-metrics.name" . }}
    helm.sh/chart: {{ include "eventhub-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ template "eventhub-metrics.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "eventhub-metrics.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
