{
 "title": "Eventhub Metrics - Consumer Group Dashboard",
 "description": "ConsumerGroup metrics exported by eventhub-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consumerGroup",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(eh_metrics_consumer_group_lag,consumer_group)"
    }
   },
   {
    "name": "eventhub",
    "label": "Eventhub",
    "query": {
     "query": "label_values(eh_metrics_consumer_group_lag{consumer_group=\"$consumerGroup\"},eventhub)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumergroup => Eventhub Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (consumer_group,eventhub) (eh_metrics_consumer_group_lag{consumer_group=\"$consumerGroup\", eventhub=\"$eventhub\"})",
     "legendFormat": "{{group_id}} => {{topic_name}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "description": "State of the group. Either empty, stable or unknown",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eh_metrics_consumer_group_info{consumer_group=\"$consumerGroup\", eventhub=\"$eventhub\"}"
    }
   ]
  },
  {
   "title": "Eventhub Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (consumer_group,eventhub) (eh_metrics_consumer_group_lag{consumer_group=\"$consumerGroup\", eventhub=\"$eventhub\"})"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (eventhub) (rate(eh_metrics_eventhub_sequence_max_sum{eventhub=\"$eventhub\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{topic_name}}"
    },
    {
     "expr": "avg by (eventhub, consumer_group) (rate(eh_metrics_consumer_group_events_sum{consumer_group=\"$consumerGroup\", eventhub=\"$eventhub\"}[$__rate_interval]))",
     "legendFormat": "Consuming: {{topic_name}}"
    }
   ]
  },
  {
   "title": "Partition Owners",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "eh_metrics_consumer_group_partition_owner{consumer_group=\"$consumerGroup\", eventhub=\"$eventhub\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}