{
 "title": "Eventhub Metrics - Eventhub Dashboard",
 "description": "Eventhub metrics exported by eventhub-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "eventhub",
    "label": "Eventhub",
    "query": {
     "query": "label_values(eh_metrics_eventhub_sequence_min_sum,eventhub)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message count",
   "type": "timeseries",
   "description": "Summed delta between Max and Min Sequence number of all partitions in the given eventhub.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (eventhub) (eh_metrics_eventhub_sequence_max_sum{eventhub=\"$eventhub\"} - eh_metrics_eventhub_sequence_min_sum{eventhub=\"$eventhub\"})",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eh_metrics_eventhub_info{eventhub=\"$eventhub\"}"
    }
   ]
  },
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (eventhub) (rate(eh_metrics_eventhub_sequence_max_sum{eventhub=\"$eventhub\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Message Retention In Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eh_metrics_eventhub_info{eventhub=\"$eventhub\"}"
    }
   ]
  },
  {
   "title": "Subscribed Consumer Groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "eh_metrics_consumer_group_lag{eventhub=\"$eventhub\"}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "avg by (partition_id) (eh_metrics_eventhub_partition_sequence_min{eventhub=\"$eventhub\"})"
    },
    {
     "expr": "avg by (partition_id) (eh_metrics_eventhub_partition_sequence_max{eventhub=\"$eventhub\"})"
    }
   ]
  }
 ]
}