{
 "title": "Eventhub Metrics - Namespace Dashboard",
 "description": "Namespace wide metrics exported by eventhub-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "highThroughputEventhubs",
    "query": {
     "query": "query_result(topk(15, avg by (eventhub) (avg_over_time(eh_metrics_eventhub_sequence_max_sum[${__range_s}s]))))"
    }
   },
   {
    "name": "topOffsetCommitters",
    "query": {
     "query": "query_result(topk(5, avg by (consumer_group) (avg_over_time(eh_metrics_consumer_group_events_sum[${__range_s}s]))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages in/sec by eventhub [Top 15]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (eventhub) (rate(eh_metrics_eventhub_sequence_max_sum{eventhub=~\"$highThroughputEventhubs\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Top Offset Committers [Top 5]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (consumer_group) (rate(eh_metrics_consumer_group_events_sum{consumer_group=~\"$topOffsetCommitters\"}[$__rate_interval]))",
     "legendFormat": "{{group_id}}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eh_metrics_namespace_info" }
   ]
  },
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(eh_metrics_eventhub_sequence_max_sum[$__rate_interval]))"
    }
   ]
  }
 ]
}