{{- if not (hasKey .Values "serviceAccountName") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eventhub-metrics.fullname" . }}
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.managedIdentity.clientId }}
{{- end }}
